name: OPA Check

on: [push]

jobs:
  opa-check:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Setup OPA
      uses: open-policy-agent/setup-opa@v2

    - name: OPA check strict
      run: opa check --strict test/

    - name: Check formatting
      run: opa fmt --diff --fail test/
