name: OPA Check

on: [push]

jobs:
  opa-check:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v5

    - name: Setup OPA
      uses: open-policy-agent/setup-opa@v2

    - name: OPA check strict
      run: opa check --strict test/

    - name: OPA test
      run: opa test --coverage --threshold 100 test/

    - name: Setup Regal
      uses: StyraInc/setup-regal@v1
      with:
        version: latest
    - run: regal lint --format github test/
